/*
###############################################################
#  Generated by:      Cadence Innovus 25.12-s079_1
#  OS:                Linux x86_64(Host ID eng-analogsim3.eecs.oregonstate.edu)
#  Generated on:      Sun Feb 22 13:17:56 2026
#  Design:            counter_4b
#  Command:           write_netlist counter_4b.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 25.12-s067_1
// Generated on: Feb 19 2026 08:47:38 PST (Feb 19 2026 16:47:38 UTC)
// Verification Directory fv/counter_4b 
module counter_4b (
	clk, 
	en, 
	rst, 
	count);
   input clk;
   input en;
   input rst;
   output [3:0] count;

   // Internal wires
   wire FE_OFN3_count_1;
   wire FE_OFN2_count_2;
   wire FE_OFN1_count_3;
   wire FE_OFN0_count_0;
   wire [3:0] int_count;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire n_0;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;

   CLKBUFX4 FE_OFC3_count_1 (.Y(count[1]),
	.A(FE_OFN3_count_1));
   CLKBUFX4 FE_OFC2_count_2 (.Y(count[2]),
	.A(FE_OFN2_count_2));
   CLKBUFX4 FE_OFC1_count_3 (.Y(count[3]),
	.A(FE_OFN1_count_3));
   CLKBUFX4 FE_OFC0_count_0 (.Y(count[0]),
	.A(FE_OFN0_count_0));
   DFFRX1 \int_count_reg[3]  (.Q(int_count[3]),
	.QN(UNCONNECTED),
	.CK(clk),
	.D(n_10),
	.RN(n_9));
   CLKXOR2X1 g227__2398 (.Y(n_10),
	.A(int_count[3]),
	.B(n_7));
   DFFRX1 \int_count_reg[2]  (.Q(int_count[2]),
	.QN(UNCONNECTED0),
	.CK(clk),
	.D(n_8),
	.RN(n_9));
   ADDHX1 g229__5107 (.CO(n_7),
	.S(n_8),
	.A(int_count[2]),
	.B(n_5));
   DFFRX1 \int_count_reg[1]  (.Q(int_count[1]),
	.QN(UNCONNECTED1),
	.CK(clk),
	.D(n_6),
	.RN(n_9));
   ADDHX1 g231__6260 (.CO(n_5),
	.S(n_6),
	.A(int_count[0]),
	.B(int_count[1]));
   DFFRX1 \int_count_reg[0]  (.Q(int_count[0]),
	.QN(n_0),
	.CK(clk),
	.D(n_0),
	.RN(n_9));
   CLKAND2X2 g235__4319 (.Y(FE_OFN3_count_1),
	.A(en),
	.B(int_count[1]));
   CLKAND2X2 g232__8428 (.Y(FE_OFN2_count_2),
	.A(en),
	.B(int_count[2]));
   CLKAND2X2 g234__5526 (.Y(FE_OFN0_count_0),
	.A(en),
	.B(int_count[0]));
   CLKAND2X2 g236__6783 (.Y(FE_OFN1_count_3),
	.A(en),
	.B(int_count[3]));
   CLKINVX1 g238 (.Y(n_9),
	.A(rst));
endmodule

